kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 8000    # gate-app
        protocol: TCP
      - containerPort: 30081
        hostPort: 8081    # redis-commander
        protocol: TCP
      - containerPort: 30082
        hostPort: 8082    # kafka-ui
        protocol: TCP

  # worker node 2ê°œ
  - role: worker
  - role: worker